### ISSUE TITLE
no process error

### ISSUE THREAD

**Issue by unenglishable** [alexfilatov/guardian_redis#3]
i got a `no process` error when trying to store and revoke tokens.  this is due to the app's redix instance not being included in the supervision tree -- luckily, i saw this configuration in #2 

```
** (exit) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
```

i've forked the repo and will be submitting a PR with changes to the README documenting how to set up supervision for redix

this change is up for debate, if redix can be configured in the overall app and shared with guardian_redis, i think that would be the best solution; otherwise, i end up with two lines in the supervision tree for redix

thanks for considering!

**Comment by alexfilatov** [comment]
approved, sorry for such late response ;(
